# Generated by Django 5.1.2 on 2024-10-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/plantes/')),
                ('type_plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantes', to='plant_disease.typeplante')),
            ],
        ),
    ]
