# Generated by Django 5.1.2 on 2024-10-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_disease', '0004_alter_pest_type_controlproduct'),
        ('plant_disease', '0004_causemaladie'),
    ]

    operations = [
    ]
