# Generated by Django 5.1.2 on 2024-10-26 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_disease', '0005_merge_20241026_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='prevention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('symptômes_connexes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures_préventives', to='plant_disease.symptome')),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('méthode', models.TextField()),
                ('maladie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitement', to='plant_disease.maladie')),
            ],
        ),
    ]
