# Generated by Django 5.1.2 on 2024-10-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_disease', '0006_symptome_prevention_traitement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diagnostic', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='plant_disease.maladie')),
                ('plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='plant_disease.plante')),
                ('traitement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostics', to='plant_disease.traitement')),
            ],
        ),
    ]
