# Generated by Django 5.1.2 on 2024-10-29 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_disease', '0007_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptome',
            name='plante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptomes', to='plant_disease.plante'),
        ),
    ]
