# Generated by Django 5.1.2 on 2024-10-29 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_disease', '0009_maladie_causes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maladie',
            name='causes',
        ),
        migrations.AddField(
            model_name='causemaladie',
            name='maladie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_maladies', to='plant_disease.maladie'),
        ),
    ]
